// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"myapp/internal/infrastructure/database/ent/helloworld"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HelloWorldCreate is the builder for creating a HelloWorld entity.
type HelloWorldCreate struct {
	config
	mutation *HelloWorldMutation
	hooks    []Hook
}

// SetLang sets the "lang" field.
func (hwc *HelloWorldCreate) SetLang(s string) *HelloWorldCreate {
	hwc.mutation.SetLang(s)
	return hwc
}

// SetMessage sets the "message" field.
func (hwc *HelloWorldCreate) SetMessage(s string) *HelloWorldCreate {
	hwc.mutation.SetMessage(s)
	return hwc
}

// Mutation returns the HelloWorldMutation object of the builder.
func (hwc *HelloWorldCreate) Mutation() *HelloWorldMutation {
	return hwc.mutation
}

// Save creates the HelloWorld in the database.
func (hwc *HelloWorldCreate) Save(ctx context.Context) (*HelloWorld, error) {
	return withHooks(ctx, hwc.sqlSave, hwc.mutation, hwc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hwc *HelloWorldCreate) SaveX(ctx context.Context) *HelloWorld {
	v, err := hwc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hwc *HelloWorldCreate) Exec(ctx context.Context) error {
	_, err := hwc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hwc *HelloWorldCreate) ExecX(ctx context.Context) {
	if err := hwc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hwc *HelloWorldCreate) check() error {
	if _, ok := hwc.mutation.Lang(); !ok {
		return &ValidationError{Name: "lang", err: errors.New(`ent: missing required field "HelloWorld.lang"`)}
	}
	if _, ok := hwc.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "HelloWorld.message"`)}
	}
	return nil
}

func (hwc *HelloWorldCreate) sqlSave(ctx context.Context) (*HelloWorld, error) {
	if err := hwc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hwc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hwc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	hwc.mutation.id = &_node.ID
	hwc.mutation.done = true
	return _node, nil
}

func (hwc *HelloWorldCreate) createSpec() (*HelloWorld, *sqlgraph.CreateSpec) {
	var (
		_node = &HelloWorld{config: hwc.config}
		_spec = sqlgraph.NewCreateSpec(helloworld.Table, sqlgraph.NewFieldSpec(helloworld.FieldID, field.TypeInt))
	)
	if value, ok := hwc.mutation.Lang(); ok {
		_spec.SetField(helloworld.FieldLang, field.TypeString, value)
		_node.Lang = value
	}
	if value, ok := hwc.mutation.Message(); ok {
		_spec.SetField(helloworld.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	return _node, _spec
}

// HelloWorldCreateBulk is the builder for creating many HelloWorld entities in bulk.
type HelloWorldCreateBulk struct {
	config
	err      error
	builders []*HelloWorldCreate
}

// Save creates the HelloWorld entities in the database.
func (hwcb *HelloWorldCreateBulk) Save(ctx context.Context) ([]*HelloWorld, error) {
	if hwcb.err != nil {
		return nil, hwcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hwcb.builders))
	nodes := make([]*HelloWorld, len(hwcb.builders))
	mutators := make([]Mutator, len(hwcb.builders))
	for i := range hwcb.builders {
		func(i int, root context.Context) {
			builder := hwcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HelloWorldMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hwcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hwcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hwcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hwcb *HelloWorldCreateBulk) SaveX(ctx context.Context) []*HelloWorld {
	v, err := hwcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hwcb *HelloWorldCreateBulk) Exec(ctx context.Context) error {
	_, err := hwcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hwcb *HelloWorldCreateBulk) ExecX(ctx context.Context) {
	if err := hwcb.Exec(ctx); err != nil {
		panic(err)
	}
}
