// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"myapp/internal/infrastructure/database/ent/sketch"
	"myapp/internal/infrastructure/database/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Sketch is the model entity for the Sketch schema.
type Sketch struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// ImageName holds the value of the "image_name" field.
	ImageName string `json:"image_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SketchQuery when eager-loading is set.
	Edges        SketchEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SketchEdges holds the relations/edges for other nodes in the graph.
type SketchEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SketchEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sketch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sketch.FieldID, sketch.FieldUserID:
			values[i] = new(sql.NullInt64)
		case sketch.FieldImageName:
			values[i] = new(sql.NullString)
		case sketch.FieldCreatedAt, sketch.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sketch fields.
func (s *Sketch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sketch.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case sketch.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case sketch.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		case sketch.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				s.UserID = int(value.Int64)
			}
		case sketch.FieldImageName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_name", values[i])
			} else if value.Valid {
				s.ImageName = value.String
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sketch.
// This includes values selected through modifiers, order, etc.
func (s *Sketch) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Sketch entity.
func (s *Sketch) QueryUser() *UserQuery {
	return NewSketchClient(s.config).QueryUser(s)
}

// Update returns a builder for updating this Sketch.
// Note that you need to call Sketch.Unwrap() before calling this method if this Sketch
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Sketch) Update() *SketchUpdateOne {
	return NewSketchClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Sketch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Sketch) Unwrap() *Sketch {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sketch is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Sketch) String() string {
	var builder strings.Builder
	builder.WriteString("Sketch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", s.UserID))
	builder.WriteString(", ")
	builder.WriteString("image_name=")
	builder.WriteString(s.ImageName)
	builder.WriteByte(')')
	return builder.String()
}

// Sketches is a parsable slice of Sketch.
type Sketches []*Sketch
