// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"myapp/internal/infrastructure/database/ent/sketch"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Sketch is the model entity for the Sketch schema.
type Sketch struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// ImageName holds the value of the "image_name" field.
	ImageName    string `json:"image_name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sketch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sketch.FieldID, sketch.FieldUserID:
			values[i] = new(sql.NullInt64)
		case sketch.FieldImageName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sketch fields.
func (s *Sketch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sketch.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case sketch.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				s.UserID = int(value.Int64)
			}
		case sketch.FieldImageName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_name", values[i])
			} else if value.Valid {
				s.ImageName = value.String
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sketch.
// This includes values selected through modifiers, order, etc.
func (s *Sketch) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Sketch.
// Note that you need to call Sketch.Unwrap() before calling this method if this Sketch
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Sketch) Update() *SketchUpdateOne {
	return NewSketchClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Sketch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Sketch) Unwrap() *Sketch {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sketch is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Sketch) String() string {
	var builder strings.Builder
	builder.WriteString("Sketch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", s.UserID))
	builder.WriteString(", ")
	builder.WriteString("image_name=")
	builder.WriteString(s.ImageName)
	builder.WriteByte(')')
	return builder.String()
}

// Sketches is a parsable slice of Sketch.
type Sketches []*Sketch
