// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"myapp/internal/controller/repository/ent/helloworld"
	"myapp/internal/controller/repository/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HelloWorldQuery is the builder for querying HelloWorld entities.
type HelloWorldQuery struct {
	config
	ctx        *QueryContext
	order      []helloworld.OrderOption
	inters     []Interceptor
	predicates []predicate.HelloWorld
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HelloWorldQuery builder.
func (hwq *HelloWorldQuery) Where(ps ...predicate.HelloWorld) *HelloWorldQuery {
	hwq.predicates = append(hwq.predicates, ps...)
	return hwq
}

// Limit the number of records to be returned by this query.
func (hwq *HelloWorldQuery) Limit(limit int) *HelloWorldQuery {
	hwq.ctx.Limit = &limit
	return hwq
}

// Offset to start from.
func (hwq *HelloWorldQuery) Offset(offset int) *HelloWorldQuery {
	hwq.ctx.Offset = &offset
	return hwq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hwq *HelloWorldQuery) Unique(unique bool) *HelloWorldQuery {
	hwq.ctx.Unique = &unique
	return hwq
}

// Order specifies how the records should be ordered.
func (hwq *HelloWorldQuery) Order(o ...helloworld.OrderOption) *HelloWorldQuery {
	hwq.order = append(hwq.order, o...)
	return hwq
}

// First returns the first HelloWorld entity from the query.
// Returns a *NotFoundError when no HelloWorld was found.
func (hwq *HelloWorldQuery) First(ctx context.Context) (*HelloWorld, error) {
	nodes, err := hwq.Limit(1).All(setContextOp(ctx, hwq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{helloworld.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hwq *HelloWorldQuery) FirstX(ctx context.Context) *HelloWorld {
	node, err := hwq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HelloWorld ID from the query.
// Returns a *NotFoundError when no HelloWorld ID was found.
func (hwq *HelloWorldQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hwq.Limit(1).IDs(setContextOp(ctx, hwq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{helloworld.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hwq *HelloWorldQuery) FirstIDX(ctx context.Context) int {
	id, err := hwq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HelloWorld entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HelloWorld entity is found.
// Returns a *NotFoundError when no HelloWorld entities are found.
func (hwq *HelloWorldQuery) Only(ctx context.Context) (*HelloWorld, error) {
	nodes, err := hwq.Limit(2).All(setContextOp(ctx, hwq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{helloworld.Label}
	default:
		return nil, &NotSingularError{helloworld.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hwq *HelloWorldQuery) OnlyX(ctx context.Context) *HelloWorld {
	node, err := hwq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HelloWorld ID in the query.
// Returns a *NotSingularError when more than one HelloWorld ID is found.
// Returns a *NotFoundError when no entities are found.
func (hwq *HelloWorldQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hwq.Limit(2).IDs(setContextOp(ctx, hwq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{helloworld.Label}
	default:
		err = &NotSingularError{helloworld.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hwq *HelloWorldQuery) OnlyIDX(ctx context.Context) int {
	id, err := hwq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HelloWorlds.
func (hwq *HelloWorldQuery) All(ctx context.Context) ([]*HelloWorld, error) {
	ctx = setContextOp(ctx, hwq.ctx, "All")
	if err := hwq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HelloWorld, *HelloWorldQuery]()
	return withInterceptors[[]*HelloWorld](ctx, hwq, qr, hwq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hwq *HelloWorldQuery) AllX(ctx context.Context) []*HelloWorld {
	nodes, err := hwq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HelloWorld IDs.
func (hwq *HelloWorldQuery) IDs(ctx context.Context) (ids []int, err error) {
	if hwq.ctx.Unique == nil && hwq.path != nil {
		hwq.Unique(true)
	}
	ctx = setContextOp(ctx, hwq.ctx, "IDs")
	if err = hwq.Select(helloworld.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hwq *HelloWorldQuery) IDsX(ctx context.Context) []int {
	ids, err := hwq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hwq *HelloWorldQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hwq.ctx, "Count")
	if err := hwq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hwq, querierCount[*HelloWorldQuery](), hwq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hwq *HelloWorldQuery) CountX(ctx context.Context) int {
	count, err := hwq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hwq *HelloWorldQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hwq.ctx, "Exist")
	switch _, err := hwq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hwq *HelloWorldQuery) ExistX(ctx context.Context) bool {
	exist, err := hwq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HelloWorldQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hwq *HelloWorldQuery) Clone() *HelloWorldQuery {
	if hwq == nil {
		return nil
	}
	return &HelloWorldQuery{
		config:     hwq.config,
		ctx:        hwq.ctx.Clone(),
		order:      append([]helloworld.OrderOption{}, hwq.order...),
		inters:     append([]Interceptor{}, hwq.inters...),
		predicates: append([]predicate.HelloWorld{}, hwq.predicates...),
		// clone intermediate query.
		sql:  hwq.sql.Clone(),
		path: hwq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HelloWorld.Query().
//		GroupBy(helloworld.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hwq *HelloWorldQuery) GroupBy(field string, fields ...string) *HelloWorldGroupBy {
	hwq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HelloWorldGroupBy{build: hwq}
	grbuild.flds = &hwq.ctx.Fields
	grbuild.label = helloworld.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.HelloWorld.Query().
//		Select(helloworld.FieldCreatedAt).
//		Scan(ctx, &v)
func (hwq *HelloWorldQuery) Select(fields ...string) *HelloWorldSelect {
	hwq.ctx.Fields = append(hwq.ctx.Fields, fields...)
	sbuild := &HelloWorldSelect{HelloWorldQuery: hwq}
	sbuild.label = helloworld.Label
	sbuild.flds, sbuild.scan = &hwq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HelloWorldSelect configured with the given aggregations.
func (hwq *HelloWorldQuery) Aggregate(fns ...AggregateFunc) *HelloWorldSelect {
	return hwq.Select().Aggregate(fns...)
}

func (hwq *HelloWorldQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hwq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hwq); err != nil {
				return err
			}
		}
	}
	for _, f := range hwq.ctx.Fields {
		if !helloworld.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hwq.path != nil {
		prev, err := hwq.path(ctx)
		if err != nil {
			return err
		}
		hwq.sql = prev
	}
	return nil
}

func (hwq *HelloWorldQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HelloWorld, error) {
	var (
		nodes = []*HelloWorld{}
		_spec = hwq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HelloWorld).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HelloWorld{config: hwq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hwq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (hwq *HelloWorldQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hwq.querySpec()
	_spec.Node.Columns = hwq.ctx.Fields
	if len(hwq.ctx.Fields) > 0 {
		_spec.Unique = hwq.ctx.Unique != nil && *hwq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hwq.driver, _spec)
}

func (hwq *HelloWorldQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(helloworld.Table, helloworld.Columns, sqlgraph.NewFieldSpec(helloworld.FieldID, field.TypeInt))
	_spec.From = hwq.sql
	if unique := hwq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hwq.path != nil {
		_spec.Unique = true
	}
	if fields := hwq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, helloworld.FieldID)
		for i := range fields {
			if fields[i] != helloworld.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hwq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hwq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hwq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hwq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hwq *HelloWorldQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hwq.driver.Dialect())
	t1 := builder.Table(helloworld.Table)
	columns := hwq.ctx.Fields
	if len(columns) == 0 {
		columns = helloworld.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hwq.sql != nil {
		selector = hwq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hwq.ctx.Unique != nil && *hwq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hwq.predicates {
		p(selector)
	}
	for _, p := range hwq.order {
		p(selector)
	}
	if offset := hwq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hwq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HelloWorldGroupBy is the group-by builder for HelloWorld entities.
type HelloWorldGroupBy struct {
	selector
	build *HelloWorldQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hwgb *HelloWorldGroupBy) Aggregate(fns ...AggregateFunc) *HelloWorldGroupBy {
	hwgb.fns = append(hwgb.fns, fns...)
	return hwgb
}

// Scan applies the selector query and scans the result into the given value.
func (hwgb *HelloWorldGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hwgb.build.ctx, "GroupBy")
	if err := hwgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HelloWorldQuery, *HelloWorldGroupBy](ctx, hwgb.build, hwgb, hwgb.build.inters, v)
}

func (hwgb *HelloWorldGroupBy) sqlScan(ctx context.Context, root *HelloWorldQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hwgb.fns))
	for _, fn := range hwgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hwgb.flds)+len(hwgb.fns))
		for _, f := range *hwgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hwgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hwgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HelloWorldSelect is the builder for selecting fields of HelloWorld entities.
type HelloWorldSelect struct {
	*HelloWorldQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hws *HelloWorldSelect) Aggregate(fns ...AggregateFunc) *HelloWorldSelect {
	hws.fns = append(hws.fns, fns...)
	return hws
}

// Scan applies the selector query and scans the result into the given value.
func (hws *HelloWorldSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hws.ctx, "Select")
	if err := hws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HelloWorldQuery, *HelloWorldSelect](ctx, hws.HelloWorldQuery, hws, hws.inters, v)
}

func (hws *HelloWorldSelect) sqlScan(ctx context.Context, root *HelloWorldQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hws.fns))
	for _, fn := range hws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
