// Code generated by ent, DO NOT EDIT.

package helloworld

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the helloworld type in the database.
	Label = "hello_world"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLang holds the string denoting the lang field in the database.
	FieldLang = "lang"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// Table holds the table name of the helloworld in the database.
	Table = "hello_worlds"
)

// Columns holds all SQL columns for helloworld fields.
var Columns = []string{
	FieldID,
	FieldLang,
	FieldMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the HelloWorld queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLang orders the results by the lang field.
func ByLang(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLang, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}
