// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// HelloWorld is the predicate function for helloworld builders.
type HelloWorld func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Sketch is the predicate function for sketch builders.
type Sketch func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
