// Code generated by ent, DO NOT EDIT.

package sketch

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sketch type in the database.
	Label = "sketch"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldImageName holds the string denoting the image_name field in the database.
	FieldImageName = "image_name"
	// Table holds the table name of the sketch in the database.
	Table = "sketches"
)

// Columns holds all SQL columns for sketch fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldImageName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Sketch queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByImageName orders the results by the image_name field.
func ByImageName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageName, opts...).ToFunc()
}
